language: node_js
node_js: "9"
cache: yarn
# before_script: yarn
# script:
#   - yarn test
#   - yarn build
# deploy:
#   provider: pages
#   github_token: $GITHUB_TOKEN
#   local_dir: dist
#   skip_cleanup: true
#   on:
#     branch: master

jobs:
  include:
    - stage: test
      before_script: yarn
      script:
        - yarn test
        - yarn build
    - stage: docs
      script: yarn docs:build
      deploy:
        provider: pages
        github_token: $GITHUB_TOKEN
        local_dir: docs/.vuepress/dist
        skip_cleanup: true
        on:
          branch: master
