language: node_js
node_js: "9"
cache: yarn
jobs:
  include:
    - stage: test
      before_script: yarn
      script:
        - yarn test
        - yarn build
      # deploy:
      #   provider: script
      #   skip_cleanup: true
      #   script:
      #     - yarn semantic-release
      deploy:
        provider: npm
        email: sebastien.lombard75@gmail.com
        api_key: $NPM_TOKEN
        skip_cleanup: true
        on:
          tags: true
    - stage: docs
      script: yarn docs:build
      deploy:
        provider: pages
        github_token: $GH_TOKEN
        local_dir: docs/.vuepress/dist
        skip_cleanup: true
        on:
          branch: master
