language: node_js
node_js: "9"
cache: yarn
jobs:
  include:
    - stage: test
      before_script: yarn
      script:
        - yarn test
        - yarn build
      script: echo "Deploying to GitHub releases ..."
      deploy:
        provider: releases
        api_key: $GITHUB_TOKEN
        skip_cleanup: true
        on:
          tags: true
    - stage: docs
      script: yarn docs:build
      deploy:
        provider: pages
        github_token: $GITHUB_TOKEN
        local_dir: docs/.vuepress/dist
        skip_cleanup: true
        on:
          branch: master
